# Generated by Django 2.0 on 2018-08-27 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('design', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modeofpayment', models.CharField(choices=[('Bank', 'Bank'), ('Meetup', 'Meetup')], max_length=256)),
                ('shipment', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=256)),
            ],
        ),
    ]
