# Generated by Django 2.0 on 2018-08-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20180820_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brandname', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='item',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portfolio.Category'),
        ),
    ]
