# Generated by Django 2.0 on 2018-09-11 02:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('carousel_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_quantity', models.IntegerField(default=0)),
                ('design', models.ImageField(blank=True, null=True, upload_to='')),
                ('report_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modeofpayment', models.CharField(choices=[('Bank', 'Bank'), ('Meetup', 'Meetup')], max_length=256, null=True)),
                ('shipment', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=256, null=True)),
            ],
        ),
    ]
