# Generated by Django 2.0 on 2018-08-27 20:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Completed', 'Completed'), ('Shipment Pending', 'Shipment Pending'), ('Payment Pending', 'Payment Pending'), ('Problem', 'Problem')], max_length=256)),
                ('Amount', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Unprocessed', 'Unprocessed'), ('Capture Failed', 'Capture Failed')], max_length=256)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
