# Generated by Django 2.0 on 2018-09-11 02:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_fname', models.CharField(max_length=30)),
                ('order_mname', models.CharField(max_length=30)),
                ('order_lname', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('order_email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 09 or '+639'. Up to 9 digits allowed.", regex='^(09|\\+639)\\d{9}$')])),
                ('order_status', models.CharField(choices=[('Completed', 'Completed'), ('Shipment Pending', 'Shipment Pending'), ('Payment Pending', 'Payment Pending'), ('Problem', 'Problem')], max_length=256)),
                ('order_amount', models.IntegerField()),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Unprocessed', 'Unprocessed')], max_length=256)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
